input-training: ../data/input_train
label-training: ../data/label_train
max-samples-training: 10000
input-validation: ../data/input_valid
label-validation: ../data/label_valid
max-samples-validation: 1000

model: model.py
epochs: 17
batch-size: 1
learning-rate: 1e-4

save-interval: 1
output-dir: output

# model-weights:

# for predict.py only
input-testing: ../data/input_test
max-samples-testing: 100
# prediction-dir:

# input point cloud
y-min: -28.16
y-max: 28.16
x-min: -40.96
x-max: 40.96
z-min: -3.0
z-max: 1.0
step-x-size: 0.16
step-y-size: 0.16
intensity-threshold: 100

# output grid map
grid-map-size-x: 256
grid-map-size-y: 176

# PointPillars Feature Net parameters #
max-points-per-pillar: 100
max-pillars: 10000
number-features: 9
number-channels: 64
