name: dlgm
channels:
  - conda-forge
  - hcc
dependencies:
  - configargparse=1.4
  - easydict=1.9
  - matplotlib=3.3.4
  - numpy=1.19.5
  - opencv=4.4.0
  - pip=21.0.1
  - pylint=2.7.4
  - python=3.7.10
  - shapely=1.7.1
  - tensorflow-gpu=2.2.0
  - tensorflow-addons=0.11.2
  - tqdm=4.59.0
  - yapf=0.31.0
  - pyyaml=5.4.1
  - pip:
    - git+https://slikaf:C9doVn4AF3hVxHjJFiGy@gitlab.ika.rwth-aachen.de/automated-driving/pointpillars.git
    - git+https://github.com/klintan/pypcd.git#egg=pypcd
