name: evilog
channels:
  - conda-forge
  - hcc
dependencies:
  - configargparse=1.4
  - matplotlib=3.3.4
  - numpy=1.19.5
  - opencv=4.4.0
  - pip=21.0.1
  - pyntcloud=0.1.4
  - python=3.7.10
  - tensorflow-gpu=2.2.0
  - tensorflow-addons=0.11.2
  - tqdm=4.59.0
  - pip:
    - git+https://github.com/ika-rwth-aachen/PointPillars.git
